spring.application.name=bikes

# LOCALE CONFIG
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# MYSQL Config
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bikes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=root
